# Generated by Django 2.0.2 on 2018-02-23 09:17

from django.db import migrations, models
import utils.date_time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='代理地址', max_length=32, unique=True)),
                ('checked_time_stamp', models.IntegerField(default=utils.date_time.now)),
            ],
            options={
                'db_table': 'proxy',
            },
        ),
    ]
